language: c
git:
  quiet: true
  depth: 1
os: linux
compiler:
- clang
- gcc
script:
- mkdir build
- cd build
- 'cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../psh "-DCMAKE_C_FLAGS_INIT=-Wall -Wextra -Wpedantic"'
- make install
- make distclean
- ../configure
- make install
- make distclean
